"""add resume storage_path

Revision ID: 3fe85525da4f
Revises: cb02f8f50e97
Create Date: 2026-07-27 12:40:14.866533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe85525da4f'
down_revision: Union[str, None] = 'cb02f8f50e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_resumes_storage_path'), 'resumes', ['storage_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_storage_path'), table_name='resumes')
    op.drop_column('resumes', 'storage_path')
    # ### end Alembic commands ###
